// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using SchoolPortal.Shared.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace SchoolPortal.Shared.Models
{
    public partial interface ISchoolNewPortalContextProcedures
    {
        Task<List<GetSundaysbyyearandmonthResult>> GetSundaysbyyearandmonthAsync(string year, string month, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_CommitToHistoryEmpAttendanceDataResult>> usp_CommitToHistoryEmpAttendanceDataAsync(int? month, int? year, string attendanceShift, int? companyID, int? schoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_CommitToHistoryEmpSalaryDataResult>> usp_CommitToHistoryEmpSalaryDataAsync(int? month, int? year, int? empDeptID, int? companyID, int? schoolID, string session, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_DeleteEmpAttendanceDataResult>> usp_DeleteEmpAttendanceDataAsync(int? month, int? year, string attendanceShift, int? companyID, int? schoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_DisplayEmpSalaryDataResult>> usp_DisplayEmpSalaryDataAsync(int? month, int? year, int? empDeptID, int? companyID, int? schoolID, string session, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_DisplayEmpSalaryHistoryDataResult>> usp_DisplayEmpSalaryHistoryDataAsync(int? month, int? year, int? empDeptID, int? companyID, int? schoolID, string session, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_GenerateEmpSalaryDataResult>> usp_GenerateEmpSalaryDataAsync(int? month, int? year, int? empDeptID, int? companyID, int? schoolID, string session, DateTime? batchPrintDate, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_GenerateEmpSalaryStrucDataResult>> usp_GenerateEmpSalaryStrucDataAsync(int? companyID, int? schoolID, string session, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_getClassSectionTimeTableHistoryDataResult>> usp_getClassSectionTimeTableHistoryDataAsync(int? sessionID, int? classID, int? secId, int? companyID, int? schoolID, string sessionYear, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_getClassSectionTimeTableHistoryRecordsResult>> usp_getClassSectionTimeTableHistoryRecordsAsync(int? sessionID, int? classID, int? secId, int? companyID, int? schoolID, string sessionYear, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_getEmpAttendanceDetailsResult>> usp_getEmpAttendanceDetailsAsync(int? month, int? year, string attendanceShift, int? companyID, int? schoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_getEmpAttendanceDetailsHistoryResult>> usp_getEmpAttendanceDetailsHistoryAsync(int? month, int? year, string attendanceShift, int? companyID, int? schoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_getEmpAttendanceRecordsResult>> usp_getEmpAttendanceRecordsAsync(int? month, int? year, string attendanceShift, int? companyID, int? schoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_getEmpAttendanceRecordsHistoryResult>> usp_getEmpAttendanceRecordsHistoryAsync(int? month, int? year, string attendanceShift, int? companyID, int? schoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_getReportCardCommentsResult>> usp_getReportCardCommentsAsync(string reportCardIDs, int? classId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_getReportCardCommentsHistoryResult>> usp_getReportCardCommentsHistoryAsync(string reportCardIDs, int? classId, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_GetStudentFeesReceiptDetailsResult>> usp_GetStudentFeesReceiptDetailsAsync(string stuGuid, int? classId, int? sectionID, int? feesMonth, int? feesYear, int? companyID, int? schoolID, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_getTeacherTimeTableHistoryDataResult>> usp_getTeacherTimeTableHistoryDataAsync(int? sessionID, int? teacherID, int? companyID, int? schoolID, string sessionYear, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_getTeacherTimeTableHistoryRecordsResult>> usp_getTeacherTimeTableHistoryRecordsAsync(int? sessionID, int? teacherID, int? companyID, int? schoolID, string sessionYear, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<usp_select_SMSTaskScheduleResult>> usp_select_SMSTaskScheduleAsync(int? day, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
