// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using SchoolPortal.Shared.Models;

namespace SchoolPortal.Shared.Models
{
    public partial class SchoolNewPortalContext
    {

        [DbFunction("fnCONVTO_ROMAN", "dbo")]
        public static string fnCONVTO_ROMAN(int? p_Number)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
